config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions
  
  root 'static_pages#home'
  
  get 'home' => 'static_pages#home'
  
  get 'about' => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'help' => 'static_pages#help'
  
  get "new_user" => 'users#new'
  
  get "sign_in" => "sessions#new", as: "signin"
  
  get "show" => "users#show", as: 'logged_in'
  
  delete 'logout', to: 'sessions#destroy', as: 'signout'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  before_save{ |user| user.email = email.downcase}
  before_save :create_remember_token
  
  #validating name
  validates(:name, presence: true, length: {maximum: 50})
  
  #validating email
  #REGEX constant validates format of email
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates(:email, presence: true, length: {minimum: 6},
  uniqueness: {case_sensitive: false}, 
  format: {with:VALID_EMAIL_REGEX})
  
  
  
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect the user's show page
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render('new')
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        sign_in @user
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    #@user.update_attributes(params.require(:user).permit(:password, :password_confirmation))
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile Successfully Updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
#    respond_to do |format|
#      if @user.update(user_params)
#        format.html { redirect_to @user, notice: 'User was successfully updated.' }
#        format.json { render :show, status: :ok, location: @user }
#      else
#        format.html { render :edit }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#      end
#    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title)
    default_title = "DIY Blog App Using Rails"
    if title.empty?
      default_title
    else
      "#{default_title} | #{title}"
    end
  end
  
  def path_find(page)
    if page == "new_user"
      return "/new_user"
    else
      "/home"
    end
  end
    
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # http://www.justinweiss.com/articles/how-rails-sessions-work/
  # ^ read this.  basically, you want to use the session object for this.
  # my understanding is the session object is a rails-managed cookie that
  # gets stored in the user side, and is way more secure than writing to cookies
  # directly (for the most part)
  def sign_in(user)
    session[:remember_token] = user.remember_token
  end

  def signed_in?
    !session[:remember_token].nil?
  end

  def current_user
    User.find_by_remember_token(session[:remember_token])
  end

  def sign_out
    session.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
  end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
	<small>
		Powered by
		<a href="http://rubyonrails.org/"> Ruby on Rails </a>
	</small>
	
	<nav>
		<ul>
			<li><%= link_to "Help", '#'%></li>
			<li><%= link_to "Contact", "#"%></li>
		</ul>	
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class = "navbar navbar-fixed-top">
	<div class = "navbar-inner">
		<div class = "container">
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", '/home'%></li>
					<li><%= link_to "About", '/about'%></li>
					<li><%= link_to "Recent Updates", '/recent_updates'%></li>
					
					
					<% if signed_in? %>
						<li><%= link_to "Users", '#'%></li>
						<li id="fat-menu" class="dropdown">
							<a href = '#' class="dropdown-toggle" data-toggle="dropdown">
								Account <b class = 'caret'></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user%></li>
								<li><%= link_to "Settings", "#" %></li>
								<li class="divider"></li>
								<li>
									<%= link_to "Sign Out", signout_path, method: "delete"%>
								</li>
								
							</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign In", signin_path%></li>
					<%end%>										
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title))%></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
	<body>
		<%= render 'layouts/header'%>
		<div class "container">
			<% flash.each do |key, value|%>
				<div class="alert alert - <%=key%> "><%= value %></div>
			<%end%>
		<%= yield %>
		<%= render 'layouts/footer'%>
		<%= debug(params) if Rails.env.development? %>
		</div>
	
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>

<% if @user.errors.any? %>
	<div id="error explanation">
		<div class="alert alert-error">
		The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
	
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>
<%end%>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'home') %>

<h1>Home Page</h1>

<div class = "center hero-unit">
	<p> DIY Blogging and Random Stuff Web Application </p>
	<%= link_to "Sign up", path_find("new_user"), class: "btn btn-large btn-primary"%>
</div>

<div class = "center hero-unit">
<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org'%>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%provide(:title, "Edit User")%>

<h1> Update Your Profile </h1>

<div class = "container">
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
	<%= form_for(@user) do |f|%>
		<%= render 'shared/error_messages'%>
		
		<%= f.label :name%>
		<%= f.text_field :name%>
		
		<%= f.label :email%>
		<%= f.text_field :email%>
		
		<%= f.label :password%>
		<%= f.password_field :password%>
		
		<%= f.label :password_confirmation, "Confirm Password"%>
		<%= f.password_field :password_confirmation%>
		
		<%= f.submit "Save Changes", class: "btn btn-large btn-primary"%>
	<%end%>
	
	
	<%= gravatar_for(@user)%>
	<a href="http://gravatar.com/emails"> Change </a>
	
	</div>
</div>
</div>
		

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% provide(:title, "Sign Up")%>
<h1>Sign Up Poor Soul</h1>

<div class = "container">
<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@user) do |f| %>
		  <%= render 'shared/error_messages' %>
		  <div class = "form-group">
		  	<%= f.label :name, raw("Your name:" )%>
		  	<%= f.text_field :name, class: 'form-control'%>
		  </div>
		  
		  <div class="form-group">
		  	<%= f.label :email, raw("Email address:")%>
		  	<%= f.text_field :email, class: 'form-control'%>
		  </div>
		  
		  <div class="form-group">
		  	<%= f.label :password, raw("Password:")%>
		  	<%= f.text_field :password, class: 'form-control'%>
		  </div>
		  
		  <div class="form-group">
		  	<%= f.label :password_confirmation, raw("Password (for confirmation):")%>
		  	<%= f.text_field :password_confirmation, class: 'form-control'%>
		  </div>
		  
		 <%= f.submit "Submit", class: "btn btn-lg btn-primary"%>
		 <%end%>	
	</div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user%>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>

<p> Options </p>
<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', users_path %>